# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sdRcpp <- function(x) {
    .Call('_ddsPLS_sdRcpp', PACKAGE = 'ddsPLS', x)
}

get_sd_matrixRcpp <- function(x) {
    .Call('_ddsPLS_get_sd_matrixRcpp', PACKAGE = 'ddsPLS', x)
}

scaleRcpp <- function(x) {
    .Call('_ddsPLS_scaleRcpp', PACKAGE = 'ddsPLS', x)
}

mmultC <- function(m1, m2) {
    .Call('_ddsPLS_mmultC', PACKAGE = 'ddsPLS', m1, m2)
}

do_one_componentCpp <- function(x0, y0, COV, lam, errorMin = 1e-9) {
    .Call('_ddsPLS_do_one_componentCpp', PACKAGE = 'ddsPLS', x0, y0, COV, lam, errorMin)
}

modelddsPLSCpp <- function(x, y, lam = 0, R = 1L, errorMin = 1e-9) {
    .Call('_ddsPLS_modelddsPLSCpp', PACKAGE = 'ddsPLS', x, y, lam, R, errorMin)
}

