# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sdC <- function(x) {
    .Call('_ddsPLS_sdC', PACKAGE = 'ddsPLS', x)
}

scaleRcpp <- function(x) {
    .Call('_ddsPLS_scaleRcpp', PACKAGE = 'ddsPLS', x)
}

mmultC <- function(m1, m2) {
    .Call('_ddsPLS_mmultC', PACKAGE = 'ddsPLS', m1, m2)
}

